Traceback (most recent call last):
  File "/media/sf_Projects/influence_api/influence_api/inf_server.py", line 11, in <module>
    from daemon import runner
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/runner.py", line 25, in <module>
    import pidlockfile
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
Traceback (most recent call last):
  File "/media/sf_Projects/influence_api/influence_api/inf_server.py", line 11, in <module>
    from daemon import runner
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/runner.py", line 25, in <module>
    import pidlockfile
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
Traceback (most recent call last):
  File "/media/sf_Projects/influence_api/influence_api/inf_server.py", line 11, in <module>
    from daemon import runner
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/runner.py", line 25, in <module>
    import pidlockfile
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
Traceback (most recent call last):
  File "/media/sf_Projects/influence_api/influence_api/inf_server.py", line 11, in <module>
    from daemon import runner
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/runner.py", line 25, in <module>
    import pidlockfile
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
Traceback (most recent call last):
  File "/media/sf_Projects/influence_api/influence_api/inf_server.py", line 11, in <module>
    from daemon import runner
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/runner.py", line 25, in <module>
    import pidlockfile
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
Traceback (most recent call last):
  File "/media/sf_Projects/influence_api/influence_api/inf_server.py", line 11, in <module>
    from daemon import runner
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/runner.py", line 25, in <module>
    import pidlockfile
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
Traceback (most recent call last):
  File "/media/sf_Projects/influence_api/influence_api/inf_server.py", line 11, in <module>
    from daemon import runner
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/runner.py", line 25, in <module>
    import pidlockfile
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
Traceback (most recent call last):
  File "/media/sf_Projects/influence_api/influence_api/inf_server.py", line 11, in <module>
    from daemon import runner
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/runner.py", line 25, in <module>
    import pidlockfile
  File "/usr/local/lib/python2.7/dist-packages/python_daemon-1.5.5-py2.7.egg/daemon/pidlockfile.py", line 33, in <module>
    class PIDLockFile(LinkFileLock, object):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
